### ISSUE TITLE
Support Sentry User Feedback Integration

### ISSUE THREAD

**Issue by tmtrademark** [stayallive/wp-sentry#201]
Hello! First off, thank you so much for the plugin! It has been hugely helpful for my company!

I'm currently investigating turning on the User Feedback integration, and I noticed that setting it by using `wp_sentry_hook` (thanks for that also btw), the SDK outputs this message:

>"You are using new Feedback() even though this bundle does not include Feedback."

I was able to successfully enable the integration by making and enqueueing my own bundle and adding back the `wp-sentry` specific JS. 

Is there any world where you would consider including a bundle with User Feedback enabled? Or perhaps pick up the conversation from #169 where you discussed allowing users to specify their own browser bundle?

Thanks!

**Comment by stayallive** [comment]
This is quickly snowballing out of hand with all the integrations 🙈

It does look like however that feedback now is officially available and also available as a bundle with replay and tracing... so I am thinking we just add this bundle too and make it easier to enable (especially since it's such a cool and nice feature).

No promises but I plan to work on this pretty soon 👍 

Just to be super clear, you are talking about the [User Feedback Widget](https://docs.sentry.io/platforms/javascript/user-feedback/#user-feedback-widget) that you'd like to enable right?

**Comment by tmtrademark** [comment]
@stayallive Yes, there certainly are a lot of integrations.

You're correct, I am talking about the User Feedback Widget and Crash Modal that you linked to.

**Comment by stayallive** [comment]
Cool, thanks! I am working on the "User Feedback Widget" for now.

The Crash Modal I am not planning at this time, don't feel like this is very interesting considering the amount of JS errors that sites generate without much effect.

But the feedback widget I am working on. Been tracking down a bug (getsentry/sentry-javascript#13080) that needs to be solved before I can finish it.

**Comment by stayallive** [comment]
Version 8 of this plugin was just released (check out the release notes [here](https://github.com/stayallive/wp-sentry/releases/tag/v8.0.0)) and the User Feedback Widget is now supported, see: https://github.com/stayallive/wp-sentry#set-up-user-feedback.
