### ISSUE TITLE
Profiles are only captured for admin pages

### ISSUE THREAD

**Issue by ootwch** [stayallive/wp-sentry#206]
I have set up the plugin according to the instructions, including starting it from wp-config and adding the mu-plugin.

**Observation:**
- I get everything I need for admin pages, including profile, traces.
- For non-admin pages I only get the browser traces

![image](https://github.com/user-attachments/assets/31e8d921-b761-41a2-b05f-c6f1125f7a9e)

![image](https://github.com/user-attachments/assets/65ef7afd-45c0-4156-97fd-e8bc2d76b7cd)

PHP Version:	8.3.6
Wordpress Version:	6.6.2

**Comment by stayallive** [comment]
In your first screenshot I do see a trace for `/` which should be your homepage. Let's ignore profiles for now since they are dependent on traces. Can you check under "Performance" in the sidebar and see if there are any transactions not from your admin? This includes `/`. Depending on how your front-end is setup there might be issues detecting the correct route names and all your transactions might be lumped under the wrong URL.

**Comment by ootwch** [comment]
![image](https://github.com/user-attachments/assets/8d3416b2-e5fe-4ebe-b2f9-96ff41e83026)

The performance tab looks good, but no profiles - or am I misunderstanding something?

![image](https://github.com/user-attachments/assets/649776cf-8932-4dff-9f13-0ec0e59b4341)

For the admin (or admin-ajax? :thinking:  ) calls it works

![image](https://github.com/user-attachments/assets/b73bcd3e-e7b9-47a9-a1fd-1327ea420caa)

I have tried to debug the code/plugin, so far I think it is doing everything correctly, and the data is sent to sentry, but I don't understand where it disappears...

At least it seems to pass through `Transaction::finish`..

Do you have any input on how to debug this?

**Comment by stayallive** [comment]
Am I seeing it right most if not all of those take 30 or more seconds? The current limit on profiling is 30 seconds which might be why profiles or not collected.

**Comment by ootwch** [comment]
Hmm... the '/' part is more around 10 seconds... still, is that a server constraint or a client limit? In other words, can I adapt it or verify if that is the cause?

**Comment by stayallive** [comment]
This should be an client limit (not 100% sure what the server does with a larger one though). 

Since you are debugging already, you can try modifying the options with the `logger` option: https://docs.sentry.io/platforms/php/configuration/options/#logger. This should create a file showing you internal SDK logs. Never use this in production of course but should help here hopefully finding out why no profiles.

**Comment by ootwch** [comment]
**For future reference: How to add debug logs to wp-sentry**
```php
function wp_sentry_clientbuilder_callback( \Sentry\ClientBuilder $builder ): void {
	$builder->getOptions()->setLogger(  new \Sentry\Logger\DebugFileLogger(filePath: __DIR__ . '/sentry.log') );
}
define( 'WP_SENTRY_CLIENTBUILDER_CALLBACK', 'wp_sentry_clientbuilder_callback' );
``` 

==> And this helps:

```
sentry/sentry: [error] Failed to send transaction [3b146c1084724308afa1ce896287a3b7] to o4507876094181376.ingest.de.sentry.io [project:xxxx]. Reason: "{"detail":"envelope exceeded size limits for type 'event' (https://develop.sentry.dev/sdk/envelopes/#size-limits)"}".
``` 

So there might not be a time limit, but there is a limit on the data and even the fastest request I have seems to exceed it.

==> not a bug

I have tried to filter the sent event with `wp_sentry_before_send` but did not manage to get it to trigger for now.

:bowing_man: Thanks for the support!

**Comment by stayallive** [comment]
This is interesting though and might be worth exploring some solutions and exploring why it's that big. 

Might be because of the profile but might also be because of the amount of breadcrumbs. It can happen but it should probably not happen ideally.
