### ISSUE TITLE
Not Catching PHP Errors or Exceptions

### ISSUE THREAD

**Issue by tekarex** [stayallive/wp-sentry#23]
Hi,

I've gone through all of the setup and can not get the plugin to capture a single PHP event. The plugin is installed and activated, and we added the following to wp-config.php:

`define( 'WP_SENTRY_DSN', "https://XXX:XXX@sentry.io/XXX");
define( 'WP_SENTRY_ERROR_TYPES', E_ALL & ~E_DEPRECATED & ~E_NOTICE & ~E_USER_DEPRECATED );
define( 'WP_SENTRY_PUBLIC_DSN', 'https://XXX@sentry.io/XXX' );
define( 'WP_SENTRY_ENV', 'production' );`

When we view source of the public pages, we are able to see the wp_sentry js variable set with the Public DNS.

Then, when we try to trigger intentional exceptions or notices in a WP plugin, the error occurs, and nothing gets reported to Sentry. It does appear to get logged to the error_log file though. 

Sample cases I've tried:
`throw new \Exception("Division by zero.");
trigger_error("Number cannot be larger than 10");`

I've triple checked that the private DSN is correct, but still no avail. Thoughts?

**Comment by stayallive** [comment]
Hey @rickvschmidt sorry for the late response, this does seem strange.

However there is a possibilty that `wp-sentry-integration` is loaded after your plugins are initialized (since WordPress load them alphabetically) so if you throw those in your plugins they might be thrown before Sentry is loaded.

You might want to try this method: https://github.com/stayallive/wp-sentry#catching-plugin-errors

Otherwise test it with the following snippet:

```php
add_action('plugins_loaded', function () {
	throw new \Exception('Hey there, Sentry!');
});
```

This always runs after all plugins are loaded.

**Comment by stayallive** [comment]
Hey @tekarex I am going to close this since a long time without a response, so I'm going to assume it's resolved. If not please open a new issue with some up-to-date information so I can take another look.
