### ISSUE TITLE
Sentry isn't logging Exceptions

### ISSUE THREAD

**Issue by sergiomensing** [stayallive/wp-sentry#27]
Hi,

We're running a local Sentry and local Wordpress with Docker but Sentry isn't logging the Errors and Exceptions. 

The plugin is successfully activated and we've double checked the DSN in `wp-config.php`.

We're throwing the exception inside `index.php` of the theme as follows:

```php
throw new \ErrorException('Hey there, Sentry!');
```

Is there maybe something we're missing?

**Comment by stayallive** [comment]
I just took a clean WP installation and added you code to the very top of the `index.php` of the twenty seventeen theme and got the event in Sentry... so there might be something missing or going wrong in transport to Sentry.

Considering you are running a local Sentry & WordPress from inside Docker. Did you confirm your WP container can reach your Sentry? It might be a networking issue.

Also if your DSN contains `https://` you do have to have a valid certificate on the other end, otherwise the request will not be made.

**Comment by sergiomensing** [comment]
Thank you for the help! It was the `https://` issue.
