### ISSUE TITLE
Limiting the registration of file errors

### ISSUE THREAD

**Issue by daru79** [stayallive/wp-sentry#34]
Hey,

is there a way to report errors caused by files located in the theme template only?

Best regards,
Daru

**Comment by stayallive** [comment]
Not out of the box no. You could use the `customize_sentry_options` filter to add a `send_callback` closure and filter out errors based on where they occurred. However you would need to check the complete stack trace to see if any part occurred or flowed through your template file to not miss side effect.

I do not have an example lying around for you. Unfortunately the documentation for the 1.x version of the Sentry PHP SDK (which this plugin uses under the hood) is a little harder to find since 2.x was released but you can find a bit more info about the `send_callback` here: https://github.com/getsentry/sentry-php/blob/1.x/docs/config.rst.

**Comment by daru79** [comment]
Thank You very much for Your answer ;) Have a good day ;)
