### ISSUE TITLE
Update sentry browser to 5.x.x version

### ISSUE THREAD

**Issue by limestreet** [stayallive/wp-sentry#36]
Hi,
are there any plans to update sentry browser to the latest version?
The current one is 5.6.1 - https://github.com/getsentry/sentry-javascript/releases

Thanks for any info

**Comment by stayallive** [comment]
Yeah, this will be in the newer 3.x version of the plugin. Since 5.x introduces a whole host of breaking changes I have decided to do this together with the massive breaking changes of the 2.x PHP SDK in a 3.x release of this plugin.

The 5.x browser SDK is already in the master branch: 76e1f0117f0f3e760af830a427fe57ba8fac6823

**Comment by Kilbourne** [comment]
Hi,
Any release date for new version? the biggest problem with v4 is the bundle size https://github.com/getsentry/sentry-javascript/issues/1552
