### ISSUE TITLE
Conflict with other plugins using composer vendor folders (ex. Woo MailerLite)

### ISSUE THREAD

**Issue by jordantrizz** [stayallive/wp-sentry#38]
After upgrading from v2.8.0 to v3.0.0 the following error is presented. It looks like a namespace conflict due to both plugins using the same library.

[STDERR] PHP Fatal error:  Cannot redeclare Clue\StreamFilter\register() (previously declared in wp-content/plugins/wp-sentry-integration/vendor/clue/stream-filter/src/functions.php:140) in wp-content/plugins/woo-mailerlite/vendor/clue/stream-filter/src/functions.php on line 127

**Comment by stayallive** [comment]
I think this is indeed because of a conflict between similar dependencies... I'll have to see how we can resolve this, this is the pain of using composer with WordPress. You might want to stick with 2.8 for now 😄

**Comment by jordantrizz** [comment]
Yea, its starting to become more common, are you able to simply rename the namespace?

**Comment by stayallive** [comment]
Well. The “issue” is both plugins depend on the cue package (directly or indirectly) and they both try to load the class which causes conflicts. 

Since all this happens inside the vendor folder this is handled by composer and there is no easy way to prefix namespaces or make them work nicely together. 

I have found a script that autoprefixes a full vendor folder but I’m still seeing if I can bent that in the shapes I need it in. 

Considering the quite big dependency tree of the new Sentry SDK having a copy of the code is not really an option too (we used to have the Sentry source directly in the plugin instead of through composer). 

Still working on it but no ETA unfortunately.

**Comment by domihagen** [comment]
Have the problem with an other dependency.

> PHP Fatal error:  Cannot redeclare GuzzleHttp\\Psr7\\_caseless_remove() (previously declared in /var/app/current/wp-content/plugins/wp-sentry-integration/vendor/guzzlehttp/psr7/src/functions.php:884) in phar:///var/app/current/wp-content/plugins/c3-cloudfront-clear-cache/libs/aws.v3.phar/GuzzleHttp/Psr7/functions.php on line 813

**Comment by stayallive** [comment]
Hey all, thanks everyone for your patience on this issue. Using composer with WordPress is a hot mess :D

I believe to have solved the issues by scoping all the dependencies to a custom namespace which should prevent any and all conflicts caused by or caused with this plugin.

Please update to 3.4.1 and let me know if that works for all of you!
