### ISSUE TITLE
for Browser JavaScript - the ability to turn off for old browser

### ISSUE THREAD

**Issue by pinkasey** [stayallive/wp-sentry#55]
I get a lot of errors from old browsers that, for instance, don't support `let`.
I would like to ignore these errors. I've decided not to waste time on them - I don't want them to even reach Sentry.io.

If i'd had installed Sentry without this plugin, I would've done something like this:
```
try {
  let x = 10;
  Sentry.init(wp_sentry);
} catch (e) {
  console.log('some feature not supported by browser - some functionality will not work on this page', e);
  //maybe also pop up a message
}
```

But since I have installed it using this plugin, I can't do that.
Is there a way to do it?
Or something similar?

BTW,
Sentry.io does include the configuration `Filter out known errors from legacy browsers ` -
I have this turned on. It doesn't solve my issue.

**Comment by stayallive** [comment]
This is not something I'm willing to implement in the plugin itself, I consider that out of scope and there is not really a good way to implement that piece of code and still use the plugin.

I see a few things you can do.

1. You can use server side user-agent parsing to not set `WP_SENTRY_PUBLIC_DSN` when the browser you wish to exclude is detected.

2. Disable the JS part of this plugin and implement that part yourself to have that piece of JS running to initialise instead of whats in this plugin.

3. Write to Sentry support to see why the inbound filters are not working because when you have setup your filters like below they should be filtered out already like you mentioned so there might be something wrong or missed, let them know.

![image](https://user-images.githubusercontent.com/1090754/80866865-5f957b80-8c91-11ea-939b-0922ff054e23.png)

**Comment by pinkasey** [comment]
@stayallive 
Thanks for the detailed reply, sorry for taking the time to respond.

I see your point, I understand why this might seem unfeasible or low ROI.
I'll take suggestion 2 to overcome this.
I'll also write to Sentry as you suggested.

I'll share my thought anyway:
One way I thought of implementing such feature is by allowing some kind of hook to be called before sentry is included client-side, and that hook can do some custom configurations (or in my case - prevent running sentry altogether).
The reason I didn't want to do this server-side is that I wanted to interact with the browser to make my decision. I don't want to rely on user-agent etc.

**Comment by stayallive** [comment]
Still not a 100% convinced, but noticed WordPress has a nice feature to prepend some inline JavaScript to a queued script, so cooked up this: stayallive/wp-sentry#56. Please let me know that was what you we're thinking.

**Comment by pinkasey** [comment]
Looks like exactly what I was hoping for!
Thanks!

(Of course if you're not convinced that's a good feature, don't merge it. In that case I'll add js-sentry without the plugin)

**Comment by stayallive** [comment]
Nah, it's all fine, looks like it was simpeler then I thought it to be.

Just release v3.6.0 with this change included. Let me know if you successfully been able to use it :)

**Comment by pinkasey** [comment]
oh wow that's fast

It will take me awhile to get to it, but I'll let you know
(probably by the end of the month)

**Comment by pinkasey** [comment]
Thank you for this feature, @stayallive !
Works like a charm
