### ISSUE TITLE
Github release != WP release

### ISSUE THREAD

**Issue by kkmuffme** [stayallive/wp-sentry#59]
Is there a reason the github release has a completely different structure from the WP release on https://wordpress.org/plugins/wp-sentry-integration/ ?

Would probably be better if both are identical to avoid confusion by users who are not 100% familiar, as the github shows up first in google results when searching for wp sentry (even before the WP page)

**Comment by stayallive** [comment]
@kkmuffme I don't understand what you mean with a completely different structure?

Are you downloading the .zip directly from GitHub? This is a .zip of the sources and is indeed not the same as the version uploaded to the WordPress plugin repository because this plugin can also be installed through composer I cannot keep those in sync (+ a lot of generated code would than need to live inside the git repository which is unneeded).

Als long as you install using the WordPress plugins dashboard and not use the .zip file from GitHub (which is labeled source code and cannot be removed since it's part of GitHub releases interface).

![image](https://user-images.githubusercontent.com/1090754/84358182-0f320780-abc7-11ea-9dba-f895af46df01.png)

I'm not sure how to improve except to maybe add the installable plugin zip to the release, but to be honest I've never had a complaint before so I'm not sure it's needed :)

**Comment by kkmuffme** [comment]
Could you perhaps include the WordPress zip in the release? (I mean the same zip we get when downloading from the WordPress repo)
So the relase will be 3 zips (the 2 you ahve now + the zip that is also available when going via the WP plugin directory)

**Comment by stayallive** [comment]
Well It might be possible, however I do not know exactly how WordPress packages up their zip files, so I'm not sure if it would help. 

As mentioned the current zips (actually zip and tarball) are automatically generated and cannot be turned off.

What is you use case exactly, are you installing plugins manually by uploading them or even extracting them manually instead of using the plugins interface or `wp` CLI to install them?

**Comment by kkmuffme** [comment]
Managing an intranet WP that does not have internet access, so I need to grab the things manually.
Since github allows me to "watch for releases" for repos, I just watch the plugin repos we use and download it from there automatically.
In most cases the WP & github zip are (almost) identical, your plugin is the first case I encountered where it's completely different :-)

**Comment by stayallive** [comment]
Interesting, let me think about this for a bit, I think there are ways to do this but I want to try and keep "build" files (all the dependencies managed by composer and other generated sources) out of the source code, so I have to think a bit on how to attach a plugin zip to the releases tab without me doing it manually (because I guarantee I'll forget every release).

Will let you know if I get that working 👍

**Comment by stayallive** [comment]
Let me know how this looks (and works):

> https://github.com/stayallive/wp-sentry/releases/tag/v3.7.0

**Comment by kkmuffme** [comment]
Perfect thank you! :-)
