### ISSUE TITLE
Sentry seems to be 'too late'

### ISSUE THREAD

**Issue by bobmulder** [stayallive/wp-sentry#77]
Hi there,

Thank you for this plugin, which helps me a lot!

Something is wrong with my webshop. I am getting random 500 responses. The logs my server makes don't show any details, just that the response was a 500. Sentry doesn't give me any message about a new issue, so I think Sentry is loaded too late to handle the (internal?) exception from Wordpress. 

I have loaded the plugin as MU plugin, as described in the readme.

Is there anything I am missing? Is there anyone who had this issue before?

Thanks in advance!

Bob

**Comment by stayallive** [comment]
Hi Bob,

The error logs on your website should show you at least some information on the 500 and why it occurs but it depends on the webserver and php configuration, however that is not the point of this issue.

But it's totally possible something in the core or maybe even your `wp-config.php` file causes issues and Sentry will always be too late to catch that unfortunately since it loads right after the core is loaded.

The "upside" is that if anything crashes there the change is extremely high your complete website will be down so it's noticeable more than errors occurring on a single page so for the purposes of error tracking and reporting we are early enough but errors caused but the core on startup will not be caught.

I understand this does not help you _at all_ but I don't have a solution except for checking the appropriate error logs of your webhost to track down what the issue is.

**Comment by bobmulder** [comment]
Thanks for your reply! I'll do some extra digging into plesks logging. 

I'm not very experienced with the implementations of sentry, but I'm curious what your thoughts are: I am using bedrock as base for my wordpress instance. Are we able to use sentry's PHP sdk for it, instead a wp plugin (which will load later because it's a plugin)? Of wouldn't it catch all wp related errors?

**Comment by stayallive** [comment]
I'm thinking about this. But you could certainly use the plain PHP SDK and initialise it right after the composer autoloader to load it as early as possible and catch those errors I think.

However, I have never used bedrock so I can't unfortunately say for sure that would work.

I am also thinking that using that method + the plugin could cause duplicate events and that we might want to do some changes to the plugin to use the existing Sentry SDK if available if it was initialised before the plugin is if that makes sense.

**Comment by bobmulder** [comment]
Thank you for sharing! I was looking at what this plugin is doing to get Sentry working for Wordpress. As far as I can see nothing much happens (nothing against your work tho!).

I'll give it a try for Bedrock and get back to you!

**Comment by stayallive** [comment]
You are exactly right 😉 

This plugin (and other framework integrations) are supposed to do at least as possible and have the PHP SDK do all the heavy lifting, so this plugin provides a little UI and configures the PHP SDK and hooks into some WP specific hooks, but that's it so any error reporting code lives in the PHP SDK itself.

Let me know if you find a good solution and if we can possibly document this if you think it would be beneficial for other people too!
