### ISSUE TITLE
Add custom data to catched exceptions not working

### ISSUE THREAD

**Issue by vyskoczilova** [stayallive/wp-sentry#81]
I'm not able to catch exceptions with additional data, somehow (or have no idea where to find them), I've tried:

```php
try {
  $user_id = my_site_get_user_id(['error' => 'test']);
} catch (InvalidData $e) {
  if (function_exists('wp_sentry_safe')) {
	  wp_sentry_safe(function (\Sentry\State\HubInterface $client) use ($e) {
		  $client->captureException($e, [
			  'extra' => [
				  'user_data' => $e->getData()
			  ]
		  ]);
	  });
  }
}
```

As in the [Sentry docs](https://docs.sentry.io/clients/php/usage/#reporting-exceptions), the event gets in, but without any additional data.

Just to mention, I'm on the free plan if it affects this functionality.

Thanks a lot for helping me out.

**Comment by stayallive** [comment]
Ah yeah. Unfortunately you are looking at the legacy documentation for the old PHP client, so that's why it's not working. Free plan should be fine!

Here is where you want to be: https://docs.sentry.io/platforms/php/enriching-events/context/#structured-context

There is a side note with this code though for which I cannot quickly find a example for in the docs. 

When you set something on the scope it's there for all subsequent captured exceptions. So if you want that little bit of extra data only for this one (which sounds likely) you need something like:

```php
if (function_exists('wp_sentry_safe')) {
    wp_sentry_safe(function (\Sentry\State\HubInterface $client) use ($e) {
        $client->withScope(function (\Sentry\State\Scope $scope) use ($client, $e) {
            $scope->setExtra('user_data', $e->getData());
            $client->captureException($e);
        });
    });
}
```

The `withScope` makes sure that everything you change on the scope get's discarded and has no effect on other exception captured. 

Use `configureScope` if you "permanently" want to add some data to the scope like the user ID or something (the plugin already adds user information to the scope, but as an example). 

Hope it helps!

**Comment by vyskoczilova** [comment]
Hi, @stayallive Thanks a lot for the help! That works just perfectly. To be honest, I haven't noticed that I've landed on the old documentation. 

I've extended the plugin readme - maybe it will help someone else too. Thanks for the great plugin & support.

**Comment by stayallive** [comment]
Yeah the banner displayed [on this page](https://docs.sentry.io/clients/php/) should probably be repeated on the subsequent pages, or the content should possibly just be removed 😅 

Anyway, thanks for contributing this back to the readme, I'm sure this will help someone in the future!
