### ISSUE TITLE
Why use theme version as `WP_SENTRY_VERSION`?

### ISSUE THREAD

**Issue by TangRufus** [stayallive/wp-sentry#9]
Why use theme version as `WP_SENTRY_VERSION`?

> `define( 'WP_SENTRY_VERSION', wp_get_theme()->get( 'Version' ) );`

source: https://github.com/stayallive/wp-sentry/blob/master/wp-sentry.php#L36

**Comment by stayallive** [comment]
Because we needed a somewhat sane default and since, in my use case, every site I develop has it's own custom theme and the theme is indicating the version of the project the theme version seems like the best version to use.

Of course you are free to define `WP_SENTRY_VERSION` yourself to overwrite this value 👍
